import { chromium } from 'playwright';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const gameFile = 'file:///' + path.join(__dirname, 'index.html').replace(/\\/g, '/');
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
await page.setViewportSize({ width: 1280, height: 720 });
await page.goto(gameFile);
await page.waitForTimeout(2000);
await page.locator('text=NOWA GRA').click();
await page.waitForTimeout(800);
await page.locator('.start-btn').click();
await page.waitForTimeout(1500);
await page.evaluate(()=>{ P.wx=640; P.wy=400; P.dir=2; });
await page.waitForTimeout(400);
fs.writeFileSync(path.join(__dirname,'test_face_down.png'), await page.screenshot());
await page.evaluate(()=>{ P.dir=1; });
await page.waitForTimeout(200);
fs.writeFileSync(path.join(__dirname,'test_face_right.png'), await page.screenshot());
console.log('shots taken');
await browser.close();
