import { chromium } from 'playwright';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const gameFile = 'file:///' + path.join(__dirname, 'index.html').replace(/\\/g, '/');
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
await page.setViewportSize({ width: 1280, height: 720 });
await page.goto(gameFile);
await page.waitForTimeout(2000);
await page.locator('text=NOWA GRA').click();
await page.waitForTimeout(800);
await page.locator('.start-btn').click();
await page.waitForTimeout(1500);
await page.evaluate(()=>{ cam.x=0; cam.y=0; });
await page.waitForTimeout(300);
fs.writeFileSync(path.join(__dirname,'bld_tl.png'), await page.screenshot());
await page.evaluate(()=>{ cam.x=800; cam.y=600; });
await page.waitForTimeout(300);
fs.writeFileSync(path.join(__dirname,'bld_mid.png'), await page.screenshot());
await page.evaluate(()=>{ cam.x=2800; cam.y=1200; });
await page.waitForTimeout(300);
fs.writeFileSync(path.join(__dirname,'bld_drip.png'), await page.screenshot());
await browser.close();
console.log('Done!');
